### ISSUE TITLE
shift phantomjs global npm install from readme to preinstall script in package.json

### ISSUE THREAD

**Issue by vanderhoop** [vanderhoop/remote_retro#10]
see http://stackoverflow.com/questions/6480549/install-dependencies-globally-and-locally-using-package-json#answer-10813149

**Comment by ianmcnally** [comment]
could use this, bru: https://www.npmjs.com/package/phantomjs-prebuilt

**Comment by ianmcnally** [comment]
#creeping

**Comment by vanderhoop** [comment]
#creep all you want, @ianmcnally ! In fact, I encourage you to creep even more. My webpack config isn't set up for hot module reloading, which pains my soul to no end! Any advice would be much appreciated!

Regarding this issue, ended up resolving it by shifting to a local phantomjs and just configuring [Wallaby](https://github.com/keathley/wallaby#phantomjs) to use the local version. commit: e92d8c6
