### ISSUE TITLE
allow users to submit action items

### ISSUE THREAD

**Issue by vanderhoop** [vanderhoop/remote_retro#38]
As a participant in a retro,
I would like to be able to submit action items for the retro,
So that the retro I am participating in can be more than a mere therapy session.

__Acceptance Criteria:__

- [x] the retro board contains a fourth column titled `@action-item` on the far right of the board
  - [x] the new action-item column is topped with a 🚀 emoticon
    - unicode for emoticon: `U+1F680`
- [ ] the select input anchored to the bottom of the screen has a fourth option, titled 'action-item'
- [x] when users have selected `action-item` from the "Category" select input and submit a new idea, that idea appears in the `@action-item` column for all participants in the retro

**Comment by damonblack** [comment]
https://github.com/vanderhoop/remote_retro/pull/48
